

INSERT INTO PROJECT VALUES (1, CURRENT_TIMESTAMP, 'Project description1', CURRENT_TIMESTAMP, 'E001', 'Project name1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, CURRENT_TIMESTAMP, 'Project description2', CURRENT_TIMESTAMP, 'E002', 'Project name2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, CURRENT_TIMESTAMP, 'Project description3', CURRENT_TIMESTAMP, 'E003', 'Project name3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, CURRENT_TIMESTAMP, 'Project description4', CURRENT_TIMESTAMP, 'E004', 'Project name4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 